/*
Export API

Export OpenAPI definitions

API version: 20.0.0
Contact: apiteam@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package export

import (
	"encoding/json"
)

// CursorPaginatedResponseExportJobItem struct for CursorPaginatedResponseExportJobItem
type CursorPaginatedResponseExportJobItem struct {
	Data       []ExportJobItem `json:"data"`
	Pagination CursorPageInfo  `json:"pagination"`
}

// NewCursorPaginatedResponseExportJobItem instantiates a new CursorPaginatedResponseExportJobItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPaginatedResponseExportJobItem(data []ExportJobItem, pagination CursorPageInfo) *CursorPaginatedResponseExportJobItem {
	this := CursorPaginatedResponseExportJobItem{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewCursorPaginatedResponseExportJobItemWithDefaults instantiates a new CursorPaginatedResponseExportJobItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPaginatedResponseExportJobItemWithDefaults() *CursorPaginatedResponseExportJobItem {
	this := CursorPaginatedResponseExportJobItem{}
	return &this
}

// GetData returns the Data field value
func (o *CursorPaginatedResponseExportJobItem) GetData() []ExportJobItem {
	if o == nil {
		var ret []ExportJobItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CursorPaginatedResponseExportJobItem) GetDataOk() ([]ExportJobItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CursorPaginatedResponseExportJobItem) SetData(v []ExportJobItem) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *CursorPaginatedResponseExportJobItem) GetPagination() CursorPageInfo {
	if o == nil {
		var ret CursorPageInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *CursorPaginatedResponseExportJobItem) GetPaginationOk() (*CursorPageInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *CursorPaginatedResponseExportJobItem) SetPagination(v CursorPageInfo) {
	o.Pagination = v
}

func (o CursorPaginatedResponseExportJobItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullableCursorPaginatedResponseExportJobItem struct {
	value *CursorPaginatedResponseExportJobItem
	isSet bool
}

func (v NullableCursorPaginatedResponseExportJobItem) Get() *CursorPaginatedResponseExportJobItem {
	return v.value
}

func (v *NullableCursorPaginatedResponseExportJobItem) Set(val *CursorPaginatedResponseExportJobItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPaginatedResponseExportJobItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPaginatedResponseExportJobItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPaginatedResponseExportJobItem(val *CursorPaginatedResponseExportJobItem) *NullableCursorPaginatedResponseExportJobItem {
	return &NullableCursorPaginatedResponseExportJobItem{value: val, isSet: true}
}

func (v NullableCursorPaginatedResponseExportJobItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPaginatedResponseExportJobItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
