/*
Export API

Export OpenAPI definitions

API version: 20.0.0
Contact: apiteam@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package export

import (
	"encoding/json"
	"time"
)

// InvoiceInformation In the case of an invoice, additional information pertaining to the invoice would be represented here.
type InvoiceInformation struct {
	// Date the payment is due
	DueDate NullableTime `json:"dueDate,omitempty"`
	// Date the invoice was issued
	InvoiceDate time.Time `json:"invoiceDate"`
	// The invoice number
	InvoiceNumber string `json:"invoiceNumber"`
	// Date the invoice was paid if the status is paid
	PaymentDate NullableTime `json:"paymentDate,omitempty"`
	// The invoice status
	Status              string                      `json:"status"`
	SupplierBankAccount NullableSupplierBankAccount `json:"supplierBankAccount,omitempty"`
}

// NewInvoiceInformation instantiates a new InvoiceInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceInformation(invoiceDate time.Time, invoiceNumber string, status string) *InvoiceInformation {
	this := InvoiceInformation{}
	this.InvoiceDate = invoiceDate
	this.InvoiceNumber = invoiceNumber
	this.Status = status
	return &this
}

// NewInvoiceInformationWithDefaults instantiates a new InvoiceInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceInformationWithDefaults() *InvoiceInformation {
	this := InvoiceInformation{}
	return &this
}

// GetDueDate returns the DueDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceInformation) GetDueDate() time.Time {
	if o == nil || o.DueDate.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.DueDate.Get()
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceInformation) GetDueDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDate.Get(), o.DueDate.IsSet()
}

// HasDueDate returns a boolean if a field has been set.
func (o *InvoiceInformation) HasDueDate() bool {
	if o != nil && o.DueDate.IsSet() {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given NullableTime and assigns it to the DueDate field.
func (o *InvoiceInformation) SetDueDate(v time.Time) {
	o.DueDate.Set(&v)
}

// SetDueDateNil sets the value for DueDate to be an explicit nil
func (o *InvoiceInformation) SetDueDateNil() {
	o.DueDate.Set(nil)
}

// UnsetDueDate ensures that no value is present for DueDate, not even an explicit nil
func (o *InvoiceInformation) UnsetDueDate() {
	o.DueDate.Unset()
}

// GetInvoiceDate returns the InvoiceDate field value
func (o *InvoiceInformation) GetInvoiceDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.InvoiceDate
}

// GetInvoiceDateOk returns a tuple with the InvoiceDate field value
// and a boolean to check if the value has been set.
func (o *InvoiceInformation) GetInvoiceDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceDate, true
}

// SetInvoiceDate sets field value
func (o *InvoiceInformation) SetInvoiceDate(v time.Time) {
	o.InvoiceDate = v
}

// GetInvoiceNumber returns the InvoiceNumber field value
func (o *InvoiceInformation) GetInvoiceNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceNumber
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value
// and a boolean to check if the value has been set.
func (o *InvoiceInformation) GetInvoiceNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceNumber, true
}

// SetInvoiceNumber sets field value
func (o *InvoiceInformation) SetInvoiceNumber(v string) {
	o.InvoiceNumber = v
}

// GetPaymentDate returns the PaymentDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceInformation) GetPaymentDate() time.Time {
	if o == nil || o.PaymentDate.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.PaymentDate.Get()
}

// GetPaymentDateOk returns a tuple with the PaymentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceInformation) GetPaymentDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentDate.Get(), o.PaymentDate.IsSet()
}

// HasPaymentDate returns a boolean if a field has been set.
func (o *InvoiceInformation) HasPaymentDate() bool {
	if o != nil && o.PaymentDate.IsSet() {
		return true
	}

	return false
}

// SetPaymentDate gets a reference to the given NullableTime and assigns it to the PaymentDate field.
func (o *InvoiceInformation) SetPaymentDate(v time.Time) {
	o.PaymentDate.Set(&v)
}

// SetPaymentDateNil sets the value for PaymentDate to be an explicit nil
func (o *InvoiceInformation) SetPaymentDateNil() {
	o.PaymentDate.Set(nil)
}

// UnsetPaymentDate ensures that no value is present for PaymentDate, not even an explicit nil
func (o *InvoiceInformation) UnsetPaymentDate() {
	o.PaymentDate.Unset()
}

// GetStatus returns the Status field value
func (o *InvoiceInformation) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InvoiceInformation) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InvoiceInformation) SetStatus(v string) {
	o.Status = v
}

// GetSupplierBankAccount returns the SupplierBankAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvoiceInformation) GetSupplierBankAccount() SupplierBankAccount {
	if o == nil || o.SupplierBankAccount.Get() == nil {
		var ret SupplierBankAccount
		return ret
	}
	return *o.SupplierBankAccount.Get()
}

// GetSupplierBankAccountOk returns a tuple with the SupplierBankAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvoiceInformation) GetSupplierBankAccountOk() (*SupplierBankAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupplierBankAccount.Get(), o.SupplierBankAccount.IsSet()
}

// HasSupplierBankAccount returns a boolean if a field has been set.
func (o *InvoiceInformation) HasSupplierBankAccount() bool {
	if o != nil && o.SupplierBankAccount.IsSet() {
		return true
	}

	return false
}

// SetSupplierBankAccount gets a reference to the given NullableSupplierBankAccount and assigns it to the SupplierBankAccount field.
func (o *InvoiceInformation) SetSupplierBankAccount(v SupplierBankAccount) {
	o.SupplierBankAccount.Set(&v)
}

// SetSupplierBankAccountNil sets the value for SupplierBankAccount to be an explicit nil
func (o *InvoiceInformation) SetSupplierBankAccountNil() {
	o.SupplierBankAccount.Set(nil)
}

// UnsetSupplierBankAccount ensures that no value is present for SupplierBankAccount, not even an explicit nil
func (o *InvoiceInformation) UnsetSupplierBankAccount() {
	o.SupplierBankAccount.Unset()
}

func (o InvoiceInformation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DueDate.IsSet() {
		toSerialize["dueDate"] = o.DueDate.Get()
	}
	if true {
		toSerialize["invoiceDate"] = o.InvoiceDate
	}
	if true {
		toSerialize["invoiceNumber"] = o.InvoiceNumber
	}
	if o.PaymentDate.IsSet() {
		toSerialize["paymentDate"] = o.PaymentDate.Get()
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.SupplierBankAccount.IsSet() {
		toSerialize["supplierBankAccount"] = o.SupplierBankAccount.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableInvoiceInformation struct {
	value *InvoiceInformation
	isSet bool
}

func (v NullableInvoiceInformation) Get() *InvoiceInformation {
	return v.value
}

func (v *NullableInvoiceInformation) Set(val *InvoiceInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceInformation(val *InvoiceInformation) *NullableInvoiceInformation {
	return &NullableInvoiceInformation{value: val, isSet: true}
}

func (v NullableInvoiceInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
