/*
Export API

Export OpenAPI definitions

API version: 20.0.0
Contact: apiteam@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package export

import (
	"encoding/json"
)

// CursorPaginatedResponseExportJob struct for CursorPaginatedResponseExportJob
type CursorPaginatedResponseExportJob struct {
	Data       []ExportJob    `json:"data"`
	Pagination CursorPageInfo `json:"pagination"`
}

// NewCursorPaginatedResponseExportJob instantiates a new CursorPaginatedResponseExportJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPaginatedResponseExportJob(data []ExportJob, pagination CursorPageInfo) *CursorPaginatedResponseExportJob {
	this := CursorPaginatedResponseExportJob{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewCursorPaginatedResponseExportJobWithDefaults instantiates a new CursorPaginatedResponseExportJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPaginatedResponseExportJobWithDefaults() *CursorPaginatedResponseExportJob {
	this := CursorPaginatedResponseExportJob{}
	return &this
}

// GetData returns the Data field value
func (o *CursorPaginatedResponseExportJob) GetData() []ExportJob {
	if o == nil {
		var ret []ExportJob
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CursorPaginatedResponseExportJob) GetDataOk() ([]ExportJob, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CursorPaginatedResponseExportJob) SetData(v []ExportJob) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *CursorPaginatedResponseExportJob) GetPagination() CursorPageInfo {
	if o == nil {
		var ret CursorPageInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *CursorPaginatedResponseExportJob) GetPaginationOk() (*CursorPageInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *CursorPaginatedResponseExportJob) SetPagination(v CursorPageInfo) {
	o.Pagination = v
}

func (o CursorPaginatedResponseExportJob) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullableCursorPaginatedResponseExportJob struct {
	value *CursorPaginatedResponseExportJob
	isSet bool
}

func (v NullableCursorPaginatedResponseExportJob) Get() *CursorPaginatedResponseExportJob {
	return v.value
}

func (v *NullableCursorPaginatedResponseExportJob) Set(val *CursorPaginatedResponseExportJob) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPaginatedResponseExportJob) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPaginatedResponseExportJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPaginatedResponseExportJob(val *CursorPaginatedResponseExportJob) *NullableCursorPaginatedResponseExportJob {
	return &NullableCursorPaginatedResponseExportJob{value: val, isSet: true}
}

func (v NullableCursorPaginatedResponseExportJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPaginatedResponseExportJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
