/*
Export API

Export OpenAPI definitions

API version: 20.0.0
Contact: apiteam@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package export

import (
	"encoding/json"
)

// SupplierV1 The supplier or merchant involved
type SupplierV1 struct {
	// Supplier account code in the accounting system
	Account NullableString `json:"account,omitempty"`
	// This is the category code that describes the merchant/supplier's activity
	CategoryCode NullableString `json:"categoryCode,omitempty"`
	// Identifier of the supplier in the accounting system
	Code NullableString `json:"code,omitempty"`
	// The 2-letter country code the merchant or supplier operates in
	Country NullableString `json:"country,omitempty"`
	// Name of the supplier or merchant
	Name NullableString `json:"name,omitempty"`
	// This is the tax identification of the supplier in their country of operation
	TaxIdentifier NullableString `json:"taxIdentifier,omitempty"`
}

// NewSupplierV1 instantiates a new SupplierV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupplierV1() *SupplierV1 {
	this := SupplierV1{}
	return &this
}

// NewSupplierV1WithDefaults instantiates a new SupplierV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupplierV1WithDefaults() *SupplierV1 {
	this := SupplierV1{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SupplierV1) GetAccount() string {
	if o == nil || o.Account.Get() == nil {
		var ret string
		return ret
	}
	return *o.Account.Get()
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SupplierV1) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Account.Get(), o.Account.IsSet()
}

// HasAccount returns a boolean if a field has been set.
func (o *SupplierV1) HasAccount() bool {
	if o != nil && o.Account.IsSet() {
		return true
	}

	return false
}

// SetAccount gets a reference to the given NullableString and assigns it to the Account field.
func (o *SupplierV1) SetAccount(v string) {
	o.Account.Set(&v)
}

// SetAccountNil sets the value for Account to be an explicit nil
func (o *SupplierV1) SetAccountNil() {
	o.Account.Set(nil)
}

// UnsetAccount ensures that no value is present for Account, not even an explicit nil
func (o *SupplierV1) UnsetAccount() {
	o.Account.Unset()
}

// GetCategoryCode returns the CategoryCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SupplierV1) GetCategoryCode() string {
	if o == nil || o.CategoryCode.Get() == nil {
		var ret string
		return ret
	}
	return *o.CategoryCode.Get()
}

// GetCategoryCodeOk returns a tuple with the CategoryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SupplierV1) GetCategoryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CategoryCode.Get(), o.CategoryCode.IsSet()
}

// HasCategoryCode returns a boolean if a field has been set.
func (o *SupplierV1) HasCategoryCode() bool {
	if o != nil && o.CategoryCode.IsSet() {
		return true
	}

	return false
}

// SetCategoryCode gets a reference to the given NullableString and assigns it to the CategoryCode field.
func (o *SupplierV1) SetCategoryCode(v string) {
	o.CategoryCode.Set(&v)
}

// SetCategoryCodeNil sets the value for CategoryCode to be an explicit nil
func (o *SupplierV1) SetCategoryCodeNil() {
	o.CategoryCode.Set(nil)
}

// UnsetCategoryCode ensures that no value is present for CategoryCode, not even an explicit nil
func (o *SupplierV1) UnsetCategoryCode() {
	o.CategoryCode.Unset()
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SupplierV1) GetCode() string {
	if o == nil || o.Code.Get() == nil {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SupplierV1) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *SupplierV1) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *SupplierV1) SetCode(v string) {
	o.Code.Set(&v)
}

// SetCodeNil sets the value for Code to be an explicit nil
func (o *SupplierV1) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *SupplierV1) UnsetCode() {
	o.Code.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SupplierV1) GetCountry() string {
	if o == nil || o.Country.Get() == nil {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SupplierV1) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *SupplierV1) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *SupplierV1) SetCountry(v string) {
	o.Country.Set(&v)
}

// SetCountryNil sets the value for Country to be an explicit nil
func (o *SupplierV1) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *SupplierV1) UnsetCountry() {
	o.Country.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SupplierV1) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SupplierV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *SupplierV1) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *SupplierV1) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *SupplierV1) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *SupplierV1) UnsetName() {
	o.Name.Unset()
}

// GetTaxIdentifier returns the TaxIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SupplierV1) GetTaxIdentifier() string {
	if o == nil || o.TaxIdentifier.Get() == nil {
		var ret string
		return ret
	}
	return *o.TaxIdentifier.Get()
}

// GetTaxIdentifierOk returns a tuple with the TaxIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SupplierV1) GetTaxIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaxIdentifier.Get(), o.TaxIdentifier.IsSet()
}

// HasTaxIdentifier returns a boolean if a field has been set.
func (o *SupplierV1) HasTaxIdentifier() bool {
	if o != nil && o.TaxIdentifier.IsSet() {
		return true
	}

	return false
}

// SetTaxIdentifier gets a reference to the given NullableString and assigns it to the TaxIdentifier field.
func (o *SupplierV1) SetTaxIdentifier(v string) {
	o.TaxIdentifier.Set(&v)
}

// SetTaxIdentifierNil sets the value for TaxIdentifier to be an explicit nil
func (o *SupplierV1) SetTaxIdentifierNil() {
	o.TaxIdentifier.Set(nil)
}

// UnsetTaxIdentifier ensures that no value is present for TaxIdentifier, not even an explicit nil
func (o *SupplierV1) UnsetTaxIdentifier() {
	o.TaxIdentifier.Unset()
}

func (o SupplierV1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account.IsSet() {
		toSerialize["account"] = o.Account.Get()
	}
	if o.CategoryCode.IsSet() {
		toSerialize["categoryCode"] = o.CategoryCode.Get()
	}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.TaxIdentifier.IsSet() {
		toSerialize["taxIdentifier"] = o.TaxIdentifier.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableSupplierV1 struct {
	value *SupplierV1
	isSet bool
}

func (v NullableSupplierV1) Get() *SupplierV1 {
	return v.value
}

func (v *NullableSupplierV1) Set(val *SupplierV1) {
	v.value = val
	v.isSet = true
}

func (v NullableSupplierV1) IsSet() bool {
	return v.isSet
}

func (v *NullableSupplierV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupplierV1(val *SupplierV1) *NullableSupplierV1 {
	return &NullableSupplierV1{value: val, isSet: true}
}

func (v NullableSupplierV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupplierV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
