/*
Export API

Export OpenAPI definitions

API version: 20.0.0
Contact: apiteam@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package export

import (
	"encoding/json"
)

// CursorPaginatedResponseExportItem struct for CursorPaginatedResponseExportItem
type CursorPaginatedResponseExportItem struct {
	Data       []ExportItem   `json:"data"`
	Pagination CursorPageInfo `json:"pagination"`
}

// NewCursorPaginatedResponseExportItem instantiates a new CursorPaginatedResponseExportItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPaginatedResponseExportItem(data []ExportItem, pagination CursorPageInfo) *CursorPaginatedResponseExportItem {
	this := CursorPaginatedResponseExportItem{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewCursorPaginatedResponseExportItemWithDefaults instantiates a new CursorPaginatedResponseExportItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPaginatedResponseExportItemWithDefaults() *CursorPaginatedResponseExportItem {
	this := CursorPaginatedResponseExportItem{}
	return &this
}

// GetData returns the Data field value
func (o *CursorPaginatedResponseExportItem) GetData() []ExportItem {
	if o == nil {
		var ret []ExportItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CursorPaginatedResponseExportItem) GetDataOk() ([]ExportItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CursorPaginatedResponseExportItem) SetData(v []ExportItem) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *CursorPaginatedResponseExportItem) GetPagination() CursorPageInfo {
	if o == nil {
		var ret CursorPageInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *CursorPaginatedResponseExportItem) GetPaginationOk() (*CursorPageInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *CursorPaginatedResponseExportItem) SetPagination(v CursorPageInfo) {
	o.Pagination = v
}

func (o CursorPaginatedResponseExportItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullableCursorPaginatedResponseExportItem struct {
	value *CursorPaginatedResponseExportItem
	isSet bool
}

func (v NullableCursorPaginatedResponseExportItem) Get() *CursorPaginatedResponseExportItem {
	return v.value
}

func (v *NullableCursorPaginatedResponseExportItem) Set(val *CursorPaginatedResponseExportItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPaginatedResponseExportItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPaginatedResponseExportItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPaginatedResponseExportItem(val *CursorPaginatedResponseExportItem) *NullableCursorPaginatedResponseExportItem {
	return &NullableCursorPaginatedResponseExportItem{value: val, isSet: true}
}

func (v NullableCursorPaginatedResponseExportItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPaginatedResponseExportItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
