/*
Export API

Export OpenAPI definitions

API version: 20.0.0
Contact: apiteam@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package export

import (
	"encoding/json"
)

// ExportItemUserV1 This applies to the person that initiated the spend. This would in most cases be the employee
type ExportItemUserV1 struct {
	// This would usually represent the employee code
	Code NullableString `json:"code,omitempty"`
	// This is the Pleo internal identifier of the user
	Id NullableString `json:"id"`
	// Full name of the user
	Name string `json:"name"`
}

// NewExportItemUserV1 instantiates a new ExportItemUserV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportItemUserV1(id NullableString, name string) *ExportItemUserV1 {
	this := ExportItemUserV1{}
	this.Id = id
	this.Name = name
	return &this
}

// NewExportItemUserV1WithDefaults instantiates a new ExportItemUserV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportItemUserV1WithDefaults() *ExportItemUserV1 {
	this := ExportItemUserV1{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExportItemUserV1) GetCode() string {
	if o == nil || o.Code.Get() == nil {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExportItemUserV1) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *ExportItemUserV1) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *ExportItemUserV1) SetCode(v string) {
	o.Code.Set(&v)
}

// SetCodeNil sets the value for Code to be an explicit nil
func (o *ExportItemUserV1) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *ExportItemUserV1) UnsetCode() {
	o.Code.Unset()
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ExportItemUserV1) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExportItemUserV1) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *ExportItemUserV1) SetId(v string) {
	o.Id.Set(&v)
}

// GetName returns the Name field value
func (o *ExportItemUserV1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExportItemUserV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExportItemUserV1) SetName(v string) {
	o.Name = v
}

func (o ExportItemUserV1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if true {
		toSerialize["id"] = o.Id.Get()
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableExportItemUserV1 struct {
	value *ExportItemUserV1
	isSet bool
}

func (v NullableExportItemUserV1) Get() *ExportItemUserV1 {
	return v.value
}

func (v *NullableExportItemUserV1) Set(val *ExportItemUserV1) {
	v.value = val
	v.isSet = true
}

func (v NullableExportItemUserV1) IsSet() bool {
	return v.isSet
}

func (v *NullableExportItemUserV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportItemUserV1(val *ExportItemUserV1) *NullableExportItemUserV1 {
	return &NullableExportItemUserV1{value: val, isSet: true}
}

func (v NullableExportItemUserV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportItemUserV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
