/*
Tax Code API

Tax Codes OpenAPI definitions

API version: 42.14.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tax_codes

import (
	"encoding/json"
)

// TaxCodeCreateUpdateModel struct for TaxCodeCreateUpdateModel
type TaxCodeCreateUpdateModel struct {
	// Boolean flag used to archive or unarchive a category (when set to true, account is not visible or usable on the platform)
	Archived bool `json:"archived"`
	// The accounting system's internal identifier of the tax code
	Code NullableString `json:"code,omitempty"`
	// Company ID the tax code is being created/updated for
	CompanyId string `json:"companyId"`
	// Ingoing tax account usually used to account for reverse VAT
	IngoingTaxAccount NullableString `json:"ingoingTaxAccount,omitempty"`
	// Name of the tax code
	Name string `json:"name"`
	// Outgoing tax account usually used to account for reverse VAT
	OutgoingTaxAccount NullableString `json:"outgoingTaxAccount,omitempty"`
	// Percentage rate applied for this tax code (This is represented in decimals and not the percentage. e.g. 20% tax rate would be 0.20)
	Rate float32 `json:"rate"`
	// Classification of this tax code
	Type string `json:"type"`
}

// NewTaxCodeCreateUpdateModel instantiates a new TaxCodeCreateUpdateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxCodeCreateUpdateModel(archived bool, companyId string, name string, rate float32, type_ string) *TaxCodeCreateUpdateModel {
	this := TaxCodeCreateUpdateModel{}
	this.Archived = archived
	this.CompanyId = companyId
	this.Name = name
	this.Rate = rate
	this.Type = type_
	return &this
}

// NewTaxCodeCreateUpdateModelWithDefaults instantiates a new TaxCodeCreateUpdateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxCodeCreateUpdateModelWithDefaults() *TaxCodeCreateUpdateModel {
	this := TaxCodeCreateUpdateModel{}
	return &this
}

// GetArchived returns the Archived field value
func (o *TaxCodeCreateUpdateModel) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *TaxCodeCreateUpdateModel) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *TaxCodeCreateUpdateModel) SetArchived(v bool) {
	o.Archived = v
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxCodeCreateUpdateModel) GetCode() string {
	if o == nil || o.Code.Get() == nil {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxCodeCreateUpdateModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *TaxCodeCreateUpdateModel) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *TaxCodeCreateUpdateModel) SetCode(v string) {
	o.Code.Set(&v)
}

// SetCodeNil sets the value for Code to be an explicit nil
func (o *TaxCodeCreateUpdateModel) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *TaxCodeCreateUpdateModel) UnsetCode() {
	o.Code.Unset()
}

// GetCompanyId returns the CompanyId field value
func (o *TaxCodeCreateUpdateModel) GetCompanyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *TaxCodeCreateUpdateModel) GetCompanyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *TaxCodeCreateUpdateModel) SetCompanyId(v string) {
	o.CompanyId = v
}

// GetIngoingTaxAccount returns the IngoingTaxAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxCodeCreateUpdateModel) GetIngoingTaxAccount() string {
	if o == nil || o.IngoingTaxAccount.Get() == nil {
		var ret string
		return ret
	}
	return *o.IngoingTaxAccount.Get()
}

// GetIngoingTaxAccountOk returns a tuple with the IngoingTaxAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxCodeCreateUpdateModel) GetIngoingTaxAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IngoingTaxAccount.Get(), o.IngoingTaxAccount.IsSet()
}

// HasIngoingTaxAccount returns a boolean if a field has been set.
func (o *TaxCodeCreateUpdateModel) HasIngoingTaxAccount() bool {
	if o != nil && o.IngoingTaxAccount.IsSet() {
		return true
	}

	return false
}

// SetIngoingTaxAccount gets a reference to the given NullableString and assigns it to the IngoingTaxAccount field.
func (o *TaxCodeCreateUpdateModel) SetIngoingTaxAccount(v string) {
	o.IngoingTaxAccount.Set(&v)
}

// SetIngoingTaxAccountNil sets the value for IngoingTaxAccount to be an explicit nil
func (o *TaxCodeCreateUpdateModel) SetIngoingTaxAccountNil() {
	o.IngoingTaxAccount.Set(nil)
}

// UnsetIngoingTaxAccount ensures that no value is present for IngoingTaxAccount, not even an explicit nil
func (o *TaxCodeCreateUpdateModel) UnsetIngoingTaxAccount() {
	o.IngoingTaxAccount.Unset()
}

// GetName returns the Name field value
func (o *TaxCodeCreateUpdateModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TaxCodeCreateUpdateModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TaxCodeCreateUpdateModel) SetName(v string) {
	o.Name = v
}

// GetOutgoingTaxAccount returns the OutgoingTaxAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxCodeCreateUpdateModel) GetOutgoingTaxAccount() string {
	if o == nil || o.OutgoingTaxAccount.Get() == nil {
		var ret string
		return ret
	}
	return *o.OutgoingTaxAccount.Get()
}

// GetOutgoingTaxAccountOk returns a tuple with the OutgoingTaxAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxCodeCreateUpdateModel) GetOutgoingTaxAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutgoingTaxAccount.Get(), o.OutgoingTaxAccount.IsSet()
}

// HasOutgoingTaxAccount returns a boolean if a field has been set.
func (o *TaxCodeCreateUpdateModel) HasOutgoingTaxAccount() bool {
	if o != nil && o.OutgoingTaxAccount.IsSet() {
		return true
	}

	return false
}

// SetOutgoingTaxAccount gets a reference to the given NullableString and assigns it to the OutgoingTaxAccount field.
func (o *TaxCodeCreateUpdateModel) SetOutgoingTaxAccount(v string) {
	o.OutgoingTaxAccount.Set(&v)
}

// SetOutgoingTaxAccountNil sets the value for OutgoingTaxAccount to be an explicit nil
func (o *TaxCodeCreateUpdateModel) SetOutgoingTaxAccountNil() {
	o.OutgoingTaxAccount.Set(nil)
}

// UnsetOutgoingTaxAccount ensures that no value is present for OutgoingTaxAccount, not even an explicit nil
func (o *TaxCodeCreateUpdateModel) UnsetOutgoingTaxAccount() {
	o.OutgoingTaxAccount.Unset()
}

// GetRate returns the Rate field value
func (o *TaxCodeCreateUpdateModel) GetRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rate
}

// GetRateOk returns a tuple with the Rate field value
// and a boolean to check if the value has been set.
func (o *TaxCodeCreateUpdateModel) GetRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rate, true
}

// SetRate sets field value
func (o *TaxCodeCreateUpdateModel) SetRate(v float32) {
	o.Rate = v
}

// GetType returns the Type field value
func (o *TaxCodeCreateUpdateModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TaxCodeCreateUpdateModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TaxCodeCreateUpdateModel) SetType(v string) {
	o.Type = v
}

func (o TaxCodeCreateUpdateModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["archived"] = o.Archived
	}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if true {
		toSerialize["companyId"] = o.CompanyId
	}
	if o.IngoingTaxAccount.IsSet() {
		toSerialize["ingoingTaxAccount"] = o.IngoingTaxAccount.Get()
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.OutgoingTaxAccount.IsSet() {
		toSerialize["outgoingTaxAccount"] = o.OutgoingTaxAccount.Get()
	}
	if true {
		toSerialize["rate"] = o.Rate
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableTaxCodeCreateUpdateModel struct {
	value *TaxCodeCreateUpdateModel
	isSet bool
}

func (v NullableTaxCodeCreateUpdateModel) Get() *TaxCodeCreateUpdateModel {
	return v.value
}

func (v *NullableTaxCodeCreateUpdateModel) Set(val *TaxCodeCreateUpdateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxCodeCreateUpdateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxCodeCreateUpdateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxCodeCreateUpdateModel(val *TaxCodeCreateUpdateModel) *NullableTaxCodeCreateUpdateModel {
	return &NullableTaxCodeCreateUpdateModel{value: val, isSet: true}
}

func (v NullableTaxCodeCreateUpdateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxCodeCreateUpdateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
