/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TeamsResponse struct {
	// A list of teams fetched for the requested page
	Teams []TeamsResponseTeams `json:"teams"`
}
