/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExpensesResponse struct {
	// A list of expenses fetched for the requested page
	Expenses []ExpensesResponseExpenses `json:"expenses"`
	Metadata *ExpensesResponseMetadata  `json:"metadata"`
}
