/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateTagGroupRequest struct {
	// This is the tag group name supplied on create
	Name string `json:"name,omitempty"`
	// These are the attributes that define a tag in this tag group
	TagAttributes []UpdateTagGroupRequestTagAttributes `json:"tagAttributes,omitempty"`
	// This flag specifies whether the tag group has been archived in the pleo system or not
	Archived bool `json:"archived,omitempty"`
}
