/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Additional metadata including pagination information
type ExpensesResponseMetadata struct {
	PageInfo *ExpensesResponseMetadataPageInfo `json:"pageInfo,omitempty"`
}
