/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TagResponseAttributeValues struct {
	// This is the internal pleo identifier of the created tag group attribute
	AttributeId string `json:"attributeId"`
	// This is the value assigned to this attribute of the tag
	Value string `json:"value"`
}
