/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExpenseResponseLines struct {
	AmountSettled *ExpenseResponseAmountSettled1 `json:"amountSettled"`
	// This is the UUID pleo accounting category identifier for this expense line, e.g. entertainment, travel etc.
	AccountId string `json:"accountId,omitempty"`
	// This is the UUID tax code identifier for this expense line
	TaxCodeId string `json:"taxCodeId,omitempty"`
	// These are additional accounting-related information pertaining to the expense, these are usually extracted from the external accounting system.
	TagIds []ExpenseResponseTagIds `json:"tagIds,omitempty"`
}
