/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExpensesUpdateRequest struct {
	// An array of unique expense UUIDs to update their statuses.
	ExpenseIds []string `json:"expenseIds"`
	// Status the expenses listed in the expenseIds field will be updated to.
	Status string `json:"status"`
}
