/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Pagination information.
type ExpensesResponseMetadataPageInfo struct {
	// The row number that should be used in the next fetch for the next page offset
	NextPageOffset float64 `json:"nextPageOffset,omitempty"`
	// The number of items returned in this page
	PageSize float64 `json:"pageSize"`
	// The total number of items mapped to the filter criteria supplied
	TotalCount float64 `json:"totalCount"`
}
