/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Expense supplier information.
type ExpenseResponseSupplier struct {
	// CIF code of the expense
	CIF string `json:"CIF,omitempty"`
	// Document number of the expense
	DocumentNumber string `json:"documentNumber,omitempty"`
}
