/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetAccountGroupResponse struct {
	// The unique UUID identifier of the account group
	Id string `json:"id"`
	// Description of the account group
	Name string `json:"name"`
	// Type key of the account group
	TypeKey string `json:"typeKey"`
	// Is the account hidden/archived for the user
	Hidden   bool                       `json:"hidden"`
	Accounts []AccountsResponseAccounts `json:"accounts,omitempty"`
}
