/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Returns a healthcheck status for a given company.
type HealthCheckResponse struct {
	Status string `json:"status"`
}
