/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type TaxCodeResponse struct {
	// The unique UUID identifier of the tax code.
	Id string `json:"id"`
	// The name of the tax.
	Name string `json:"name"`
	// The short code of the tax.
	Code string `json:"code,omitempty"`
	// This is the rate of the tax code.
	Rate float64 `json:"rate"`
	// This is the type of the tax code. Can be \"normal\" or \"reverse\".
	Type_ string `json:"type,omitempty"`
	// This is the ingoing account related to the tax codes.
	IngoingTaxAccount string `json:"ingoingTaxAccount,omitempty"`
	// This is the outgoing account related to the tax codes.
	OutgoingTaxAccount string `json:"outgoingTaxAccount,omitempty"`
	// This value is true if the tax code is not hidden.
	Enabled bool `json:"enabled"`
	// Date and time this record was created in the pleo system in the format YYYY-MM-DDTHH:mi:ss.SSSZ
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Date and time this record was last updated in the pleo system in the format YYYY-MM-DDTHH:mi:ss.SSSZ
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Date and time this record was deleted in the pleo system in the format YYYY-MM-DDTHH:mi:ss.SSSZ
	DeletedAt time.Time `json:"deletedAt,omitempty"`
}
