/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmployeeResponse struct {
	// The unique UUID identifier of the employee
	Id string `json:"id"`
	// Employee first name
	FirstName string `json:"firstName,omitempty"`
	// Employee last name
	LastName string `json:"lastName,omitempty"`
	// Email
	Email string `json:"email,omitempty"`
	// Job title
	JobTitle string `json:"jobTitle,omitempty"`
	// Role
	Role string `json:"role,omitempty"`
	// Phone number
	Phone  string                  `json:"phone,omitempty"`
	Avatar *EmployeeResponseAvatar `json:"avatar,omitempty"`
	// External Id
	Code string `json:"code,omitempty"`
	// Team identifier
	TeamId string `json:"teamId,omitempty"`
}
