/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CompanyBalance struct {
	// Company wallet currency.
	Currency string `json:"currency"`
	// All available funds including unsettled transactions.
	Current float64 `json:"current"`
	// Funds available for use.
	Available float64 `json:"available"`
}
