/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponse struct {
	StatusCode float64 `json:"statusCode,omitempty"`
	Error_     string  `json:"error,omitempty"`
	Message    string  `json:"message,omitempty"`
}
