/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// This is the card transaction details of this expense specifically related CARD expense types.
type ExpenseResponseCardTransaction struct {
	// This is the transaction state of this card transaction.
	State string `json:"state"`
	// Date and time the transaction was authorized in the format YYYY-MM-DDTHH:mi:ss.SSSZ.
	AuthorizedAt time.Time `json:"authorizedAt,omitempty"`
	// Date and time the transaction was settled in the pleo wallet currency in the format YYYY-MM-DDTHH:mi:ss.SSSZ.
	SettledAt time.Time `json:"settledAt,omitempty"`
	// Date and time the transaction was reversed if the transaction is in a reversal state in the format YYYY-MM-DDTHH:mi:ss.SSSZ.
	ReversedAt time.Time                               `json:"reversedAt,omitempty"`
	Merchant   *ExpenseResponseCardTransactionMerchant `json:"merchant"`
}
