/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TeamResponse struct {
	// The unique UUID identifier of the department
	Id string `json:"id"`
	// Name of the department
	Name string `json:"name"`
	// Code of the department
	Code string `json:"code,omitempty"`
	// Team employee
	Employees []EmployeesResponseEmployees `json:"employees,omitempty"`
	// Team reviewers
	Reviewers []EmployeesResponseEmployees `json:"reviewers,omitempty"`
}
