/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Receipt struct {
	// The unique UUID identifier of the receipt
	Id string `json:"id"`
	// File name of the receipt
	Name string `json:"name"`
	// Download URL of the receipt (remains valid for 15 hours)
	Url string `json:"url"`
	// Mime type of the file
	MimeType string `json:"mimeType"`
	// Size of the file in KB
	Size float64 `json:"size"`
}
