/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TagGroupCreationRequestTagAttributes struct {
	// This is the tag group name
	Name string `json:"name"`
	// This number specifies the order in which these attributes are displayed in pleo.
	DisplayOrder float64 `json:"displayOrder,omitempty"`
}
