/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountGroupsResponse struct {
	AccountGroups []AccountGroupsResponseAccountGroups `json:"accountGroups,omitempty"`
	Metadata      *ExpensesResponseMetadata            `json:"metadata"`
}
