/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TagGroupResponseTagAttributes struct {
	// This is the internal pleo identifier of the tag group
	Id string `json:"id"`
	// This is the tag group name supplied on create
	Name string `json:"name"`
	// This number specifies the order in which these attributes are displayed in pleo.
	DisplayOrder float64 `json:"displayOrder"`
	// This flag specifies the column used as a display value for the customer when applying the tag on an expense. Non-hidden column values will be concatenated and used as the display
	Hidden bool `json:"hidden"`
}
