/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TaxCodesResponse struct {
	// A list of tax codes fetched for the requested page
	TaxCodes []TaxCodesResponseTaxCodes `json:"taxCodes"`
}
