/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The breakdown settlement amount and currency for this expense line
type ExpenseResponseAmountSettled1 struct {
	Value float64 `json:"value"`
	// 3-Letter currency code
	Currency string `json:"currency"`
}
