/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TagUpdateRequest struct {
	// This is the display order position for this tag when displayed in a list.
	DisplayOrder float64 `json:"displayOrder,omitempty"`
	// This flag specifies if the tag is hidden and not visible for use in pleo when tagging expenses.
	Hidden bool `json:"hidden,omitempty"`
}
