/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountGroupCreationRequest struct {
	// Description of the account group
	Name string `json:"name,omitempty"`
	// Type key of the account group
	TypeKey string `json:"typeKey,omitempty"`
	// Is the account hidden/archived for the user
	Hidden bool `json:"hidden,omitempty"`
}
