/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmployeesResponse struct {
	Employees []EmployeesResponseEmployees `json:"employees,omitempty"`
	Metadata  *ExpensesResponseMetadata    `json:"metadata"`
}
