/*
 * Pleo.io API
 *
 * Pleo.io API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TagResponse struct {
	// This is the internal pleo identifier of the tag
	Id string `json:"id"`
	// This is the internal pleo identifier of the tag group this tag belongs to
	TagGroupId string `json:"tagGroupId"`
	// These are the attributes and their values assigned to this tag
	AttributeValues []TagResponseAttributeValues `json:"attributeValues"`
	// This is the display order position for this tag when displayed in a list.
	DisplayOrder float64 `json:"displayOrder"`
	// This flag specifies if the tag is hidden and not visible for use in pleo when tagging expenses.
	Hidden bool `json:"hidden"`
}
