/*
App Marketplace API

API for Pleo App Marketplace

API version: 29.4.0
Contact: partner-ecosystem-team@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marketplace

import (
	"encoding/json"

	"github.com/dieagenturverwaltung/pleo-api/shared"
)

// InstallationResponse struct for InstallationResponse
type InstallationResponse struct {
	// The unique identifier of the application this installation is for
	ApplicationId string `json:"applicationId"`
	// The date and time the installation was created
	CreatedAt shared.Time `json:"createdAt"`
	// The text to indicate why installation is inactive
	ErrorCode *string `json:"errorCode,omitempty"`
	// The unique identifier of the installation
	Id string `json:"id"`
	// The metadata of the installation
	Metadata map[string]map[string]interface{} `json:"metadata"`
	// The resource that the installation is for
	Resource string `json:"resource"`
	// The status of the installation
	Status string `json:"status"`
	// The date and time the installation was last updated
	UpdatedAt shared.Time `json:"updatedAt"`
}

// NewInstallationResponse instantiates a new InstallationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallationResponse(applicationId string, createdAt shared.Time, id string, metadata map[string]map[string]interface{}, resource string, status string, updatedAt shared.Time) *InstallationResponse {
	this := InstallationResponse{}
	this.ApplicationId = applicationId
	this.CreatedAt = createdAt
	this.Id = id
	this.Metadata = metadata
	this.Resource = resource
	this.Status = status
	this.UpdatedAt = updatedAt
	return &this
}

// NewInstallationResponseWithDefaults instantiates a new InstallationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallationResponseWithDefaults() *InstallationResponse {
	this := InstallationResponse{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *InstallationResponse) GetApplicationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetApplicationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *InstallationResponse) SetApplicationId(v string) {
	o.ApplicationId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *InstallationResponse) GetCreatedAt() shared.Time {
	if o == nil {
		var ret shared.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetCreatedAtOk() (*shared.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *InstallationResponse) SetCreatedAt(v shared.Time) {
	o.CreatedAt = v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *InstallationResponse) GetErrorCode() string {
	if o == nil || o.ErrorCode == nil {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetErrorCodeOk() (*string, bool) {
	if o == nil || o.ErrorCode == nil {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *InstallationResponse) HasErrorCode() bool {
	if o != nil && o.ErrorCode != nil {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *InstallationResponse) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetId returns the Id field value
func (o *InstallationResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InstallationResponse) SetId(v string) {
	o.Id = v
}

// GetMetadata returns the Metadata field value
func (o *InstallationResponse) GetMetadata() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetMetadataOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *InstallationResponse) SetMetadata(v map[string]map[string]interface{}) {
	o.Metadata = v
}

// GetResource returns the Resource field value
func (o *InstallationResponse) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *InstallationResponse) SetResource(v string) {
	o.Resource = v
}

// GetStatus returns the Status field value
func (o *InstallationResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InstallationResponse) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *InstallationResponse) GetUpdatedAt() shared.Time {
	if o == nil {
		var ret shared.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *InstallationResponse) GetUpdatedAtOk() (*shared.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *InstallationResponse) SetUpdatedAt(v shared.Time) {
	o.UpdatedAt = v
}

func (o InstallationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["applicationId"] = o.ApplicationId
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["resource"] = o.Resource
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableInstallationResponse struct {
	value *InstallationResponse
	isSet bool
}

func (v NullableInstallationResponse) Get() *InstallationResponse {
	return v.value
}

func (v *NullableInstallationResponse) Set(val *InstallationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallationResponse(val *InstallationResponse) *NullableInstallationResponse {
	return &NullableInstallationResponse{value: val, isSet: true}
}

func (v NullableInstallationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
