/*
App Marketplace API

API for Pleo App Marketplace

API version: 29.4.0
Contact: partner-ecosystem-team@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marketplace

import (
	"encoding/json"
)

// CreateClientInstallationRequest struct for CreateClientInstallationRequest
type CreateClientInstallationRequest struct {
	// The error code to indicate why installation is INACTIVE. Can only be set when status is INACTIVE.
	ErrorCode *string `json:"errorCode,omitempty"`
	// Metadata associated with the installation. This can be used to store additional information about the installation, for example  external references, but it is not used by any Pleo system
	Metadata map[string]map[string]interface{} `json:"metadata,omitempty"`
	// The status of the installation. If it is ACTIVATED, it means that the application is installed and operational.
	Status *string `json:"status,omitempty"`
}

// NewCreateClientInstallationRequest instantiates a new CreateClientInstallationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClientInstallationRequest() *CreateClientInstallationRequest {
	this := CreateClientInstallationRequest{}
	var status string = "ACTIVATED"
	this.Status = &status
	return &this
}

// NewCreateClientInstallationRequestWithDefaults instantiates a new CreateClientInstallationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClientInstallationRequestWithDefaults() *CreateClientInstallationRequest {
	this := CreateClientInstallationRequest{}
	var status string = "ACTIVATED"
	this.Status = &status
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *CreateClientInstallationRequest) GetErrorCode() string {
	if o == nil || o.ErrorCode == nil {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClientInstallationRequest) GetErrorCodeOk() (*string, bool) {
	if o == nil || o.ErrorCode == nil {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *CreateClientInstallationRequest) HasErrorCode() bool {
	if o != nil && o.ErrorCode != nil {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *CreateClientInstallationRequest) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateClientInstallationRequest) GetMetadata() map[string]map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClientInstallationRequest) GetMetadataOk() (map[string]map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateClientInstallationRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]map[string]interface{} and assigns it to the Metadata field.
func (o *CreateClientInstallationRequest) SetMetadata(v map[string]map[string]interface{}) {
	o.Metadata = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateClientInstallationRequest) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClientInstallationRequest) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateClientInstallationRequest) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateClientInstallationRequest) SetStatus(v string) {
	o.Status = &v
}

func (o CreateClientInstallationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableCreateClientInstallationRequest struct {
	value *CreateClientInstallationRequest
	isSet bool
}

func (v NullableCreateClientInstallationRequest) Get() *CreateClientInstallationRequest {
	return v.value
}

func (v *NullableCreateClientInstallationRequest) Set(val *CreateClientInstallationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClientInstallationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClientInstallationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClientInstallationRequest(val *CreateClientInstallationRequest) *NullableCreateClientInstallationRequest {
	return &NullableCreateClientInstallationRequest{value: val, isSet: true}
}

func (v NullableCreateClientInstallationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClientInstallationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
