/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// AggregatedTagTagDimensionModel List of all the dimensions and dimension values associated with the tag
type AggregatedTagTagDimensionModel struct {
	// External identifier of the Tag group Dimension used for mapping to accounting system
	Code string `json:"code"`
	// Determines the order in which the dimensions are displayed in the UI. Starts from 1
	DisplayOrder int32 `json:"displayOrder"`
	// Unique identifier of Tag Group Dimension
	Id string `json:"id"`
	// User readable name of Tag Group Dimension
	Name string `json:"name"`
	// Value of the given dimension for the given tag
	Value string `json:"value"`
	// Determines if this dimension is displayed in the UI
	Visible bool `json:"visible"`
}

// NewAggregatedTagTagDimensionModel instantiates a new AggregatedTagTagDimensionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregatedTagTagDimensionModel(code string, displayOrder int32, id string, name string, value string, visible bool) *AggregatedTagTagDimensionModel {
	this := AggregatedTagTagDimensionModel{}
	this.Code = code
	this.DisplayOrder = displayOrder
	this.Id = id
	this.Name = name
	this.Value = value
	this.Visible = visible
	return &this
}

// NewAggregatedTagTagDimensionModelWithDefaults instantiates a new AggregatedTagTagDimensionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregatedTagTagDimensionModelWithDefaults() *AggregatedTagTagDimensionModel {
	this := AggregatedTagTagDimensionModel{}
	return &this
}

// GetCode returns the Code field value
func (o *AggregatedTagTagDimensionModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagTagDimensionModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *AggregatedTagTagDimensionModel) SetCode(v string) {
	o.Code = v
}

// GetDisplayOrder returns the DisplayOrder field value
func (o *AggregatedTagTagDimensionModel) GetDisplayOrder() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DisplayOrder
}

// GetDisplayOrderOk returns a tuple with the DisplayOrder field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagTagDimensionModel) GetDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayOrder, true
}

// SetDisplayOrder sets field value
func (o *AggregatedTagTagDimensionModel) SetDisplayOrder(v int32) {
	o.DisplayOrder = v
}

// GetId returns the Id field value
func (o *AggregatedTagTagDimensionModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagTagDimensionModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AggregatedTagTagDimensionModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AggregatedTagTagDimensionModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagTagDimensionModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AggregatedTagTagDimensionModel) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *AggregatedTagTagDimensionModel) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagTagDimensionModel) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AggregatedTagTagDimensionModel) SetValue(v string) {
	o.Value = v
}

// GetVisible returns the Visible field value
func (o *AggregatedTagTagDimensionModel) GetVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagTagDimensionModel) GetVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visible, true
}

// SetVisible sets field value
func (o *AggregatedTagTagDimensionModel) SetVisible(v bool) {
	o.Visible = v
}

func (o AggregatedTagTagDimensionModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["displayOrder"] = o.DisplayOrder
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["visible"] = o.Visible
	}
	return json.Marshal(toSerialize)
}

type NullableAggregatedTagTagDimensionModel struct {
	value *AggregatedTagTagDimensionModel
	isSet bool
}

func (v NullableAggregatedTagTagDimensionModel) Get() *AggregatedTagTagDimensionModel {
	return v.value
}

func (v *NullableAggregatedTagTagDimensionModel) Set(val *AggregatedTagTagDimensionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregatedTagTagDimensionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregatedTagTagDimensionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregatedTagTagDimensionModel(val *AggregatedTagTagDimensionModel) *NullableAggregatedTagTagDimensionModel {
	return &NullableAggregatedTagTagDimensionModel{value: val, isSet: true}
}

func (v NullableAggregatedTagTagDimensionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregatedTagTagDimensionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
