/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// DataResponseListTagGroupModel struct for DataResponseListTagGroupModel
type DataResponseListTagGroupModel struct {
	Data []TagGroupModel `json:"data"`
}

// NewDataResponseListTagGroupModel instantiates a new DataResponseListTagGroupModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataResponseListTagGroupModel(data []TagGroupModel) *DataResponseListTagGroupModel {
	this := DataResponseListTagGroupModel{}
	this.Data = data
	return &this
}

// NewDataResponseListTagGroupModelWithDefaults instantiates a new DataResponseListTagGroupModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataResponseListTagGroupModelWithDefaults() *DataResponseListTagGroupModel {
	this := DataResponseListTagGroupModel{}
	return &this
}

// GetData returns the Data field value
func (o *DataResponseListTagGroupModel) GetData() []TagGroupModel {
	if o == nil {
		var ret []TagGroupModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DataResponseListTagGroupModel) GetDataOk() ([]TagGroupModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DataResponseListTagGroupModel) SetData(v []TagGroupModel) {
	o.Data = v
}

func (o DataResponseListTagGroupModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableDataResponseListTagGroupModel struct {
	value *DataResponseListTagGroupModel
	isSet bool
}

func (v NullableDataResponseListTagGroupModel) Get() *DataResponseListTagGroupModel {
	return v.value
}

func (v *NullableDataResponseListTagGroupModel) Set(val *DataResponseListTagGroupModel) {
	v.value = val
	v.isSet = true
}

func (v NullableDataResponseListTagGroupModel) IsSet() bool {
	return v.isSet
}

func (v *NullableDataResponseListTagGroupModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataResponseListTagGroupModel(val *DataResponseListTagGroupModel) *NullableDataResponseListTagGroupModel {
	return &NullableDataResponseListTagGroupModel{value: val, isSet: true}
}

func (v NullableDataResponseListTagGroupModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataResponseListTagGroupModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
