/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"

	"github.com/dieagenturverwaltung/pleo-api/shared"
)

// AggregatedTagModel struct for AggregatedTagModel
type AggregatedTagModel struct {
	// This tag is not used anymore
	Archived bool `json:"archived"`
	// External identifier of the Tag
	Code string `json:"code"`
	// Unique identifier of the company the Tag Group belongs to
	CompanyId string `json:"companyId"`
	// Creation date and time
	CreatedAt shared.Time `json:"createdAt"`
	// List of all the dimensions and dimension values associated with the tag
	Dimensions []AggregatedTagTagDimensionModel `json:"dimensions"`
	Group      AggregatedTagTagGroupModel       `json:"group"`
	// Unique identifier of Tag
	Id string `json:"id"`
	// User readable name that is used for the possible value within a tag group on an expense
	Name *string `json:"name,omitempty"`
	// Date and time of the last update
	UpdatedAt shared.Time `json:"updatedAt"`
}

// NewAggregatedTagModel instantiates a new AggregatedTagModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregatedTagModel(archived bool, code string, companyId string, createdAt shared.Time, dimensions []AggregatedTagTagDimensionModel, group AggregatedTagTagGroupModel, id string, updatedAt shared.Time) *AggregatedTagModel {
	this := AggregatedTagModel{}
	this.Archived = archived
	this.Code = code
	this.CompanyId = companyId
	this.CreatedAt = createdAt
	this.Dimensions = dimensions
	this.Group = group
	this.Id = id
	this.UpdatedAt = updatedAt
	return &this
}

// NewAggregatedTagModelWithDefaults instantiates a new AggregatedTagModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregatedTagModelWithDefaults() *AggregatedTagModel {
	this := AggregatedTagModel{}
	return &this
}

// GetArchived returns the Archived field value
func (o *AggregatedTagModel) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *AggregatedTagModel) SetArchived(v bool) {
	o.Archived = v
}

// GetCode returns the Code field value
func (o *AggregatedTagModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *AggregatedTagModel) SetCode(v string) {
	o.Code = v
}

// GetCompanyId returns the CompanyId field value
func (o *AggregatedTagModel) GetCompanyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetCompanyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *AggregatedTagModel) SetCompanyId(v string) {
	o.CompanyId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AggregatedTagModel) GetCreatedAt() shared.Time {
	if o == nil {
		var ret shared.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetCreatedAtOk() (*shared.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AggregatedTagModel) SetCreatedAt(v shared.Time) {
	o.CreatedAt = v
}

// GetDimensions returns the Dimensions field value
func (o *AggregatedTagModel) GetDimensions() []AggregatedTagTagDimensionModel {
	if o == nil {
		var ret []AggregatedTagTagDimensionModel
		return ret
	}

	return o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetDimensionsOk() ([]AggregatedTagTagDimensionModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dimensions, true
}

// SetDimensions sets field value
func (o *AggregatedTagModel) SetDimensions(v []AggregatedTagTagDimensionModel) {
	o.Dimensions = v
}

// GetGroup returns the Group field value
func (o *AggregatedTagModel) GetGroup() AggregatedTagTagGroupModel {
	if o == nil {
		var ret AggregatedTagTagGroupModel
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetGroupOk() (*AggregatedTagTagGroupModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *AggregatedTagModel) SetGroup(v AggregatedTagTagGroupModel) {
	o.Group = v
}

// GetId returns the Id field value
func (o *AggregatedTagModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AggregatedTagModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AggregatedTagModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AggregatedTagModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AggregatedTagModel) SetName(v string) {
	o.Name = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AggregatedTagModel) GetUpdatedAt() shared.Time {
	if o == nil {
		var ret shared.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AggregatedTagModel) GetUpdatedAtOk() (*shared.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AggregatedTagModel) SetUpdatedAt(v shared.Time) {
	o.UpdatedAt = v
}

func (o AggregatedTagModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["archived"] = o.Archived
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["companyId"] = o.CompanyId
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["dimensions"] = o.Dimensions
	}
	if true {
		toSerialize["group"] = o.Group
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableAggregatedTagModel struct {
	value *AggregatedTagModel
	isSet bool
}

func (v NullableAggregatedTagModel) Get() *AggregatedTagModel {
	return v.value
}

func (v *NullableAggregatedTagModel) Set(val *AggregatedTagModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregatedTagModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregatedTagModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregatedTagModel(val *AggregatedTagModel) *NullableAggregatedTagModel {
	return &NullableAggregatedTagModel{value: val, isSet: true}
}

func (v NullableAggregatedTagModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregatedTagModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
