/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// TagCreateModel struct for TagCreateModel
type TagCreateModel struct {
	// This tag is not used anymore
	Archived bool `json:"archived"`
	// External identifier of the Tag
	Code string `json:"code"`
	// User readable name that is used for the possible value within a tag group on an expense
	Name *string `json:"name,omitempty"`
}

// NewTagCreateModel instantiates a new TagCreateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCreateModel(archived bool, code string) *TagCreateModel {
	this := TagCreateModel{}
	this.Archived = archived
	this.Code = code
	return &this
}

// NewTagCreateModelWithDefaults instantiates a new TagCreateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCreateModelWithDefaults() *TagCreateModel {
	this := TagCreateModel{}
	return &this
}

// GetArchived returns the Archived field value
func (o *TagCreateModel) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *TagCreateModel) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *TagCreateModel) SetArchived(v bool) {
	o.Archived = v
}

// GetCode returns the Code field value
func (o *TagCreateModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TagCreateModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TagCreateModel) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TagCreateModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagCreateModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TagCreateModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TagCreateModel) SetName(v string) {
	o.Name = &v
}

func (o TagCreateModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["archived"] = o.Archived
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableTagCreateModel struct {
	value *TagCreateModel
	isSet bool
}

func (v NullableTagCreateModel) Get() *TagCreateModel {
	return v.value
}

func (v *NullableTagCreateModel) Set(val *TagCreateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCreateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCreateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCreateModel(val *TagCreateModel) *NullableTagCreateModel {
	return &NullableTagCreateModel{value: val, isSet: true}
}

func (v NullableTagCreateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCreateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
