/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// TagGroupUpdateModel struct for TagGroupUpdateModel
type TagGroupUpdateModel struct {
	Archived bool              `json:"archived"`
	Code     string            `json:"code"`
	Metadata map[string]string `json:"metadata"`
	Name     string            `json:"name"`
}

// NewTagGroupUpdateModel instantiates a new TagGroupUpdateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagGroupUpdateModel(archived bool, code string, metadata map[string]string, name string) *TagGroupUpdateModel {
	this := TagGroupUpdateModel{}
	this.Archived = archived
	this.Code = code
	this.Metadata = metadata
	this.Name = name
	return &this
}

// NewTagGroupUpdateModelWithDefaults instantiates a new TagGroupUpdateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagGroupUpdateModelWithDefaults() *TagGroupUpdateModel {
	this := TagGroupUpdateModel{}
	return &this
}

// GetArchived returns the Archived field value
func (o *TagGroupUpdateModel) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *TagGroupUpdateModel) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *TagGroupUpdateModel) SetArchived(v bool) {
	o.Archived = v
}

// GetCode returns the Code field value
func (o *TagGroupUpdateModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TagGroupUpdateModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TagGroupUpdateModel) SetCode(v string) {
	o.Code = v
}

// GetMetadata returns the Metadata field value
func (o *TagGroupUpdateModel) GetMetadata() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *TagGroupUpdateModel) GetMetadataOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *TagGroupUpdateModel) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetName returns the Name field value
func (o *TagGroupUpdateModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TagGroupUpdateModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TagGroupUpdateModel) SetName(v string) {
	o.Name = v
}

func (o TagGroupUpdateModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["archived"] = o.Archived
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableTagGroupUpdateModel struct {
	value *TagGroupUpdateModel
	isSet bool
}

func (v NullableTagGroupUpdateModel) Get() *TagGroupUpdateModel {
	return v.value
}

func (v *NullableTagGroupUpdateModel) Set(val *TagGroupUpdateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTagGroupUpdateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTagGroupUpdateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagGroupUpdateModel(val *TagGroupUpdateModel) *NullableTagGroupUpdateModel {
	return &NullableTagGroupUpdateModel{value: val, isSet: true}
}

func (v NullableTagGroupUpdateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagGroupUpdateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
