/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// TagGroupDimensionUpdateModel struct for TagGroupDimensionUpdateModel
type TagGroupDimensionUpdateModel struct {
	// External identifier of the Tag group Dimension used for mapping to accounting system
	Code string `json:"code"`
	// Determines the order in which the dimensions are displayed in the UI. Starts from 1
	DisplayOrder int32 `json:"displayOrder"`
	// User readable name of Tag Group Dimension
	Name string `json:"name"`
	// Determines if this dimension is displayed in the UI
	Visible bool `json:"visible"`
}

// NewTagGroupDimensionUpdateModel instantiates a new TagGroupDimensionUpdateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagGroupDimensionUpdateModel(code string, displayOrder int32, name string, visible bool) *TagGroupDimensionUpdateModel {
	this := TagGroupDimensionUpdateModel{}
	this.Code = code
	this.DisplayOrder = displayOrder
	this.Name = name
	this.Visible = visible
	return &this
}

// NewTagGroupDimensionUpdateModelWithDefaults instantiates a new TagGroupDimensionUpdateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagGroupDimensionUpdateModelWithDefaults() *TagGroupDimensionUpdateModel {
	this := TagGroupDimensionUpdateModel{}
	return &this
}

// GetCode returns the Code field value
func (o *TagGroupDimensionUpdateModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionUpdateModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TagGroupDimensionUpdateModel) SetCode(v string) {
	o.Code = v
}

// GetDisplayOrder returns the DisplayOrder field value
func (o *TagGroupDimensionUpdateModel) GetDisplayOrder() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DisplayOrder
}

// GetDisplayOrderOk returns a tuple with the DisplayOrder field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionUpdateModel) GetDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayOrder, true
}

// SetDisplayOrder sets field value
func (o *TagGroupDimensionUpdateModel) SetDisplayOrder(v int32) {
	o.DisplayOrder = v
}

// GetName returns the Name field value
func (o *TagGroupDimensionUpdateModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionUpdateModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TagGroupDimensionUpdateModel) SetName(v string) {
	o.Name = v
}

// GetVisible returns the Visible field value
func (o *TagGroupDimensionUpdateModel) GetVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionUpdateModel) GetVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visible, true
}

// SetVisible sets field value
func (o *TagGroupDimensionUpdateModel) SetVisible(v bool) {
	o.Visible = v
}

func (o TagGroupDimensionUpdateModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["displayOrder"] = o.DisplayOrder
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["visible"] = o.Visible
	}
	return json.Marshal(toSerialize)
}

type NullableTagGroupDimensionUpdateModel struct {
	value *TagGroupDimensionUpdateModel
	isSet bool
}

func (v NullableTagGroupDimensionUpdateModel) Get() *TagGroupDimensionUpdateModel {
	return v.value
}

func (v *NullableTagGroupDimensionUpdateModel) Set(val *TagGroupDimensionUpdateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTagGroupDimensionUpdateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTagGroupDimensionUpdateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagGroupDimensionUpdateModel(val *TagGroupDimensionUpdateModel) *NullableTagGroupDimensionUpdateModel {
	return &NullableTagGroupDimensionUpdateModel{value: val, isSet: true}
}

func (v NullableTagGroupDimensionUpdateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagGroupDimensionUpdateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
