/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"

	"github.com/dieagenturverwaltung/pleo-api/shared"
)

// TagGroupDimensionModel struct for TagGroupDimensionModel
type TagGroupDimensionModel struct {
	// External identifier of the Tag group Dimension used for mapping to accounting system
	Code string `json:"code"`
	// Creation date and time
	CreatedAt shared.Time `json:"createdAt"`
	// Determines the order in which the dimensions are displayed in the UI. Starts from 1
	DisplayOrder int32 `json:"displayOrder"`
	// Unique identifier of the Tag Group this dimension belongs to
	GroupId string `json:"groupId"`
	// Unique identifier of Tag Group Dimension (generated on creation)
	Id string `json:"id"`
	// User readable name of Tag Group Dimension
	Name string `json:"name"`
	// Date and time of the last update
	UpdatedAt shared.Time `json:"updatedAt"`
	// Determines if this dimension is displayed in the UI
	Visible bool `json:"visible"`
}

// NewTagGroupDimensionModel instantiates a new TagGroupDimensionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagGroupDimensionModel(code string, createdAt shared.Time, displayOrder int32, groupId string, id string, name string, updatedAt shared.Time, visible bool) *TagGroupDimensionModel {
	this := TagGroupDimensionModel{}
	this.Code = code
	this.CreatedAt = createdAt
	this.DisplayOrder = displayOrder
	this.GroupId = groupId
	this.Id = id
	this.Name = name
	this.UpdatedAt = updatedAt
	this.Visible = visible
	return &this
}

// NewTagGroupDimensionModelWithDefaults instantiates a new TagGroupDimensionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagGroupDimensionModelWithDefaults() *TagGroupDimensionModel {
	this := TagGroupDimensionModel{}
	return &this
}

// GetCode returns the Code field value
func (o *TagGroupDimensionModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TagGroupDimensionModel) SetCode(v string) {
	o.Code = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TagGroupDimensionModel) GetCreatedAt() shared.Time {
	if o == nil {
		var ret shared.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetCreatedAtOk() (*shared.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TagGroupDimensionModel) SetCreatedAt(v shared.Time) {
	o.CreatedAt = v
}

// GetDisplayOrder returns the DisplayOrder field value
func (o *TagGroupDimensionModel) GetDisplayOrder() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DisplayOrder
}

// GetDisplayOrderOk returns a tuple with the DisplayOrder field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayOrder, true
}

// SetDisplayOrder sets field value
func (o *TagGroupDimensionModel) SetDisplayOrder(v int32) {
	o.DisplayOrder = v
}

// GetGroupId returns the GroupId field value
func (o *TagGroupDimensionModel) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *TagGroupDimensionModel) SetGroupId(v string) {
	o.GroupId = v
}

// GetId returns the Id field value
func (o *TagGroupDimensionModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TagGroupDimensionModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TagGroupDimensionModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TagGroupDimensionModel) SetName(v string) {
	o.Name = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TagGroupDimensionModel) GetUpdatedAt() shared.Time {
	if o == nil {
		var ret shared.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetUpdatedAtOk() (*shared.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TagGroupDimensionModel) SetUpdatedAt(v shared.Time) {
	o.UpdatedAt = v
}

// GetVisible returns the Visible field value
func (o *TagGroupDimensionModel) GetVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value
// and a boolean to check if the value has been set.
func (o *TagGroupDimensionModel) GetVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visible, true
}

// SetVisible sets field value
func (o *TagGroupDimensionModel) SetVisible(v bool) {
	o.Visible = v
}

func (o TagGroupDimensionModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["displayOrder"] = o.DisplayOrder
	}
	if true {
		toSerialize["groupId"] = o.GroupId
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if true {
		toSerialize["visible"] = o.Visible
	}
	return json.Marshal(toSerialize)
}

type NullableTagGroupDimensionModel struct {
	value *TagGroupDimensionModel
	isSet bool
}

func (v NullableTagGroupDimensionModel) Get() *TagGroupDimensionModel {
	return v.value
}

func (v *NullableTagGroupDimensionModel) Set(val *TagGroupDimensionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTagGroupDimensionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTagGroupDimensionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagGroupDimensionModel(val *TagGroupDimensionModel) *NullableTagGroupDimensionModel {
	return &NullableTagGroupDimensionModel{value: val, isSet: true}
}

func (v NullableTagGroupDimensionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagGroupDimensionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
