/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// TagUpdateModel struct for TagUpdateModel
type TagUpdateModel struct {
	// This tag is not used anymore
	Archived bool `json:"archived"`
	// External identifier of the Tag
	Code string `json:"code"`
	// User readable name that is used for the possible value within a tag group on an expense
	Name *string `json:"name,omitempty"`
}

// NewTagUpdateModel instantiates a new TagUpdateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagUpdateModel(archived bool, code string) *TagUpdateModel {
	this := TagUpdateModel{}
	this.Archived = archived
	this.Code = code
	return &this
}

// NewTagUpdateModelWithDefaults instantiates a new TagUpdateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagUpdateModelWithDefaults() *TagUpdateModel {
	this := TagUpdateModel{}
	return &this
}

// GetArchived returns the Archived field value
func (o *TagUpdateModel) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *TagUpdateModel) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *TagUpdateModel) SetArchived(v bool) {
	o.Archived = v
}

// GetCode returns the Code field value
func (o *TagUpdateModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TagUpdateModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TagUpdateModel) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TagUpdateModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagUpdateModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TagUpdateModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TagUpdateModel) SetName(v string) {
	o.Name = &v
}

func (o TagUpdateModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["archived"] = o.Archived
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableTagUpdateModel struct {
	value *TagUpdateModel
	isSet bool
}

func (v NullableTagUpdateModel) Get() *TagUpdateModel {
	return v.value
}

func (v *NullableTagUpdateModel) Set(val *TagUpdateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTagUpdateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTagUpdateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagUpdateModel(val *TagUpdateModel) *NullableTagUpdateModel {
	return &NullableTagUpdateModel{value: val, isSet: true}
}

func (v NullableTagUpdateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagUpdateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
