/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// DataResponseListTagGroupDimensionModel struct for DataResponseListTagGroupDimensionModel
type DataResponseListTagGroupDimensionModel struct {
	Data []TagGroupDimensionModel `json:"data"`
}

// NewDataResponseListTagGroupDimensionModel instantiates a new DataResponseListTagGroupDimensionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataResponseListTagGroupDimensionModel(data []TagGroupDimensionModel) *DataResponseListTagGroupDimensionModel {
	this := DataResponseListTagGroupDimensionModel{}
	this.Data = data
	return &this
}

// NewDataResponseListTagGroupDimensionModelWithDefaults instantiates a new DataResponseListTagGroupDimensionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataResponseListTagGroupDimensionModelWithDefaults() *DataResponseListTagGroupDimensionModel {
	this := DataResponseListTagGroupDimensionModel{}
	return &this
}

// GetData returns the Data field value
func (o *DataResponseListTagGroupDimensionModel) GetData() []TagGroupDimensionModel {
	if o == nil {
		var ret []TagGroupDimensionModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DataResponseListTagGroupDimensionModel) GetDataOk() ([]TagGroupDimensionModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DataResponseListTagGroupDimensionModel) SetData(v []TagGroupDimensionModel) {
	o.Data = v
}

func (o DataResponseListTagGroupDimensionModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableDataResponseListTagGroupDimensionModel struct {
	value *DataResponseListTagGroupDimensionModel
	isSet bool
}

func (v NullableDataResponseListTagGroupDimensionModel) Get() *DataResponseListTagGroupDimensionModel {
	return v.value
}

func (v *NullableDataResponseListTagGroupDimensionModel) Set(val *DataResponseListTagGroupDimensionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableDataResponseListTagGroupDimensionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableDataResponseListTagGroupDimensionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataResponseListTagGroupDimensionModel(val *DataResponseListTagGroupDimensionModel) *NullableDataResponseListTagGroupDimensionModel {
	return &NullableDataResponseListTagGroupDimensionModel{value: val, isSet: true}
}

func (v NullableDataResponseListTagGroupDimensionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataResponseListTagGroupDimensionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
