/*
Tags API

Tags OpenAPI definitions

API version: 31.38.0
Contact: team-expense-core@pleo.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tags

import (
	"encoding/json"
)

// TagGroupCreateModel struct for TagGroupCreateModel
type TagGroupCreateModel struct {
	Archived bool               `json:"archived"`
	Code     string             `json:"code"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	Name     string             `json:"name"`
}

// NewTagGroupCreateModel instantiates a new TagGroupCreateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagGroupCreateModel(archived bool, code string, name string) *TagGroupCreateModel {
	this := TagGroupCreateModel{}
	this.Archived = archived
	this.Code = code
	this.Name = name
	return &this
}

// NewTagGroupCreateModelWithDefaults instantiates a new TagGroupCreateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagGroupCreateModelWithDefaults() *TagGroupCreateModel {
	this := TagGroupCreateModel{}
	return &this
}

// GetArchived returns the Archived field value
func (o *TagGroupCreateModel) GetArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *TagGroupCreateModel) GetArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *TagGroupCreateModel) SetArchived(v bool) {
	o.Archived = v
}

// GetCode returns the Code field value
func (o *TagGroupCreateModel) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TagGroupCreateModel) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TagGroupCreateModel) SetCode(v string) {
	o.Code = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *TagGroupCreateModel) GetMetadata() map[string]string {
	if o == nil || o.Metadata == nil {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagGroupCreateModel) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *TagGroupCreateModel) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *TagGroupCreateModel) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetName returns the Name field value
func (o *TagGroupCreateModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TagGroupCreateModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TagGroupCreateModel) SetName(v string) {
	o.Name = v
}

func (o TagGroupCreateModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["archived"] = o.Archived
	}
	if true {
		toSerialize["code"] = o.Code
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableTagGroupCreateModel struct {
	value *TagGroupCreateModel
	isSet bool
}

func (v NullableTagGroupCreateModel) Get() *TagGroupCreateModel {
	return v.value
}

func (v *NullableTagGroupCreateModel) Set(val *TagGroupCreateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTagGroupCreateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTagGroupCreateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagGroupCreateModel(val *TagGroupCreateModel) *NullableTagGroupCreateModel {
	return &NullableTagGroupCreateModel{value: val, isSet: true}
}

func (v NullableTagGroupCreateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagGroupCreateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
